/**
 * The panel's icons, each from its own file. The package index is what a skin imports at
 * compile time, 14,000 names loaded on demand (skin/icons.ts); the panel must not import
 * that index, or the bundler folds the whole set into the panel's own script.
 */
export { default as Alert02Icon } from "@hugeicons/core-free-icons/Alert02Icon"
export { default as ArtificialIntelligence01Icon } from "@hugeicons/core-free-icons/ArtificialIntelligence01Icon"
export { default as Add01Icon } from "@hugeicons/core-free-icons/Add01Icon"
export { default as ArrowLeft01Icon } from "@hugeicons/core-free-icons/ArrowLeft01Icon"
export { default as Cancel01Icon } from "@hugeicons/core-free-icons/Cancel01Icon"
export { default as DollarReceive01Icon } from "@hugeicons/core-free-icons/DollarReceive01Icon"
export { default as DollarSend01Icon } from "@hugeicons/core-free-icons/DollarSend01Icon"
export { default as Robot01Icon } from "@hugeicons/core-free-icons/Robot01Icon"
export { default as Sorting01Icon } from "@hugeicons/core-free-icons/Sorting01Icon"
export { default as SortingAZ01Icon } from "@hugeicons/core-free-icons/SortingAZ01Icon"
export { default as Tick02Icon } from "@hugeicons/core-free-icons/Tick02Icon"
export { default as CheckListIcon } from "@hugeicons/core-free-icons/CheckListIcon"
export { default as CssFile01Icon } from "@hugeicons/core-free-icons/CssFile01Icon"
export { default as Cursor01Icon } from "@hugeicons/core-free-icons/Cursor01Icon"
export { default as Delete02Icon } from "@hugeicons/core-free-icons/Delete02Icon"
export { default as Edit02Icon } from "@hugeicons/core-free-icons/Edit02Icon"
export { default as Globe02Icon } from "@hugeicons/core-free-icons/Globe02Icon"
export { default as Key01Icon } from "@hugeicons/core-free-icons/Key01Icon"
export { default as Layers01Icon } from "@hugeicons/core-free-icons/Layers01Icon"
export { default as MinusSignIcon } from "@hugeicons/core-free-icons/MinusSignIcon"
export { default as PackageIcon } from "@hugeicons/core-free-icons/PackageIcon"
export { default as PaintBrush01Icon } from "@hugeicons/core-free-icons/PaintBrush01Icon"
export { default as PaletteIcon } from "@hugeicons/core-free-icons/PaletteIcon"
export { default as Settings02Icon } from "@hugeicons/core-free-icons/Settings02Icon"
export { default as SourceCodeIcon } from "@hugeicons/core-free-icons/SourceCodeIcon"
export { default as Structure01Icon } from "@hugeicons/core-free-icons/Structure01Icon"
export { default as TextAlignLeft01Icon } from "@hugeicons/core-free-icons/TextAlignLeft01Icon"
export { default as ViewIcon } from "@hugeicons/core-free-icons/ViewIcon"
export { default as Wrench01Icon } from "@hugeicons/core-free-icons/Wrench01Icon"
